const MH="Market-hours fallback: Mon–Sat 09:00–17:30 · Sun closed";
const T=[
["Arcade","10–13","Pumphreys Coffee","eat","Historic Newcastle coffee roaster and brewing counter.",MH],
["Arcade","14–15","Olivers Café","eat","Traditional market café serving straightforward breakfast and lunch fare.",MH],
["Arcade","16","Supastitch","service","Alterations and clothing repair specialist.",MH],
["Arcade","17–18","S Murray Jewellers","shop","Independent jeweller for jewellery sales, repairs and advice.","Mon 10:30–16:45 · Tue–Sat 09:30–16:45 · Sun closed"],
["Arcade","19","Pet Lamb Patisserie","eat","Independent patisserie known for cakes, brownies and sweet bakes.","Mon closed · Tue 13:00–16:00 · Wed–Sat 09:30–16:00 · Sun closed"],
["Arcade","23–24","Matthew’s Cheese","groceries","Long-established cheese counter with British and continental cheeses.",MH],
["Arcade","25–26","Youngs Traditional Cobbler","service","Traditional shoe repairs, key cutting and leather repairs.",MH],
["Arcade","27","The French Oven","eat","Bakery selling sourdough, stotties, pastries, sausage rolls and more.","Mon–Sat from 08:00 · closing time varies · Sun closed"],
["Arcade","28–29","Hutchinson’s","groceries","Long-standing market food trader with a traditional counter.",MH],
["Arcade","187/A","Robinson’s Pet Store","shop","Independent pet shop serving generations of Newcastle customers.",MH],
["Arcade","D–E","Hunters Deli","groceries","Deli counter for cooked meats, cheeses and prepared foods.",MH],
["Arcade","F","Eats Cafe","eat","Classic market café for breakfasts, lunches and tea under the Arcade roof.","Mon–Sat 08:00–17:00 · Sun closed"],
["Arcade","G","The Coffee Lounge","eat","Traditional café for bacon sandwiches, tea, scones and simple lunches.","Mon–Sat 08:30–16:00 · Sun closed"],
["Arcade","H","Dunn's Hairdressers","service","Long-running hair salon in the Grainger Arcade.",MH],
["Arcade","Plant stall","M J Fagan Plants & Flowers","shop","Plants, flowers and seasonal colour in the main Arcade.",MH],
["Alley 4","141–142","Little Bazaar","shop","Small independent store with gifts, accessories and eclectic finds.","Mon–Sat 09:30–16:00 · Sun closed"],
["Alley 4","143–144","Tender Hooligan","shop","Independent clothing store with distinctive streetwear and local character.",MH],
["Alley 4","145","That Retro Game Shop","shop","Retro and modern games, consoles and gaming collectibles.",MH],
["Alley 4","146–147","Slice","eat","Neapolitan-style pizza served by the slice.","Mon–Sat 09:30–16:00 · Sun closed"],
["Alley 4","148–149","Finlay’s Quality Butcher","groceries","Traditional butcher focused on responsibly sourced meat.","Mon–Sat from 07:30 · closing time varies · Sun closed"],
["Alley 4","152–153","Bags of Bags","shop","Suitcases, rucksacks, shopping trolleys and everyday luggage.",MH],
["Alley 4","163","Botanical Apothecary","shop","Botanical wellbeing products made with herbs, petals and plant ingredients.","Trader-published schedule varies; currently requires confirmation"],
["Alley 4","167–168","Tian’s Gifts","shop","Asian-inspired gifts and colourful independent retail.",MH],
["Alley 4","169–172","Geordie Banger Co","groceries","Local sausage specialist and family-run food business.",MH],
["Alley 4","173–175","Crepes Gourmet","eat","Sweet and savoury crepes cooked fresh to order.","Tue–Sat 10:30–16:30 · Mon/Sun closed"],
["Alley 4","176","Mobile Pro","service","Phone and device repairs, troubleshooting and accessories.",MH],
["Alley 4","177","Geordie Gifts","shop","Tyneside-themed gifts, souvenirs and local humour.",MH],
["Alley 4","178–179","Lady Grainger","shop","Ladies’ clothing and seasonal fashion accessories.","Mon–Sat 09:00–17:00 · Sun closed"],
["Alley 4","180–181","The Battery Shop","shop","Batteries and power solutions for watches, gadgets and devices.",MH],
["Alley 3","94–95","Lily Jacques - for your baby","shop","Family-run babywear and childrenswear specialist.",MH],
["Alley 3","99–100","Petticoat Lane","shop","Independent fashion and clothing stall.",MH],
["Alley 3","103","Native African Convenience Store","groceries","African groceries, pantry ingredients and convenience goods.",MH],
["Alley 3","104–105","Pick Thai","eat","Thai street-food counter serving freshly cooked dishes.","Mon–Thu 11:00–16:30 · Fri–Sat 11:00–17:00 · Sun closed"],
["Alley 3","108","Oliver & Eden","groceries","Family butcher with a long history in the meat trade.","Mon–Sat from 07:00 · closing time varies · Sun closed"],
["Alley 3","109–110","Let It Be Music","shop","Independent record and music shop.",MH],
["Alley 3","111–112","Analog","shop","Vintage clothing including workwear, streetwear and graphic pieces.",MH],
["Alley 3","113–114","Bao Down","eat","Asian-fusion street food centred on bao and bold flavours.",MH],
["Alley 3","115","Ian Wood Memorials","service","Family-run memorial and engraving business with a long market history.",MH],
["Alley 3","117 / 164","Bryan Muers Fruiterers","groceries","Long-established family greengrocer selling fresh fruit and vegetables.",MH,"Published unit reference is unusually broad and needs physical verification."],
["Alley 3","118–124","Café one2one","eat","Central market café serving everyday breakfasts, lunches and drinks.",MH],
["Alley 3","125–156","Hector Hall","groceries","Fruit and vegetable trader known for colourful seasonal produce and value.",MH,"Published unit reference is unusually broad and needs physical verification."],
["Alley 3","128","Creations for Occasions","shop","Handmade gifts, cards and items for celebrations and special occasions.",MH],
["Alley 3","129–131","Wool on the Tyne","shop","Yarn, knitting and craft supplies; formerly known as Habiknit.",MH],
["Alley 3","132","Grainger Barbers","service","Independent barber shop in the market.",MH],
["Alley 3","133–138","Marks & Spencers Penny Bazaar","shop","The surviving historic M&S Penny Bazaar unit and a distinctive market landmark.",MH],
["Alley 2","48 / 139","Cheap Tab Shop","shop","Traditional tobacco and convenience retail stall.",MH],
["Alley 2","49–50","Redheads Mac N Cheese","eat","Comfort-food counter specialising in macaroni cheese.",MH],
["Alley 2","51–53","Fantastic Toys & Collectables","shop","Toys, models and collectible items, including harder-to-find pieces.",MH],
["Alley 2","56–57","Scented Melts","shop","Home-fragrance stall selling wax melts and scented products.","Mon 11:00–17:00 · Tue–Fri 10:00–17:00 · Sat 10:00–17:30 · Sun closed"],
["Alley 2","61","The Forest Boost","eat","Brazilian-influenced juice, smoothie and healthy-food business.","Mon–Sat 10:00–16:30 · Sun closed","Official Grainger Market page says Unit 61; another current listing says Units 73–74."],
["Alley 2","62","Manhua Cha!","eat","Bubble tea and Asian-style drinks.",MH],
["Alley 2","63–65","The Sock Factory","shop","Value socks, hosiery and everyday clothing basics.","Mon–Thu & Sat 10:00–16:00 · Fri closed · Sun closed"],
["Alley 2","66–67","Midsommar Bakery","eat","Former bakery unit; Midsommar ceased trading in August 2026.","Closed","Closed 8 Aug 2026; unit occupancy now needs re-checking."],
["Alley 2","68–69","Grainger Gifts","shop","Gift and souvenir stall.",MH],
["Alley 2","72","Recent Relics","shop","Vintage, retro and collectible items.",MH],
["Alley 2","75","Meeting You","shop","Small independent trader listed in the official market directory.",MH],
["Alley 2","76–77","Soul Rebel","shop","Independent fashion and lifestyle retail.",MH],
["Alley 2","78","Universal Export","shop","Comic-book and pop-culture shop.",MH],
["Alley 2","79","Amblergem","shop","Independent jeweller run by long-standing market traders.",MH],
["Alley 2","80–81","Firebrick Brewery","groceries","North East craft beer and lager retailer.",MH],
["Alley 2","82–83","Ilyas Fashion","shop","Family-run fashion business sourcing clothing and accessories.",MH],
["Alley 2","84","Komono Accessories","shop","Accessories and small fashion items.",MH],
["Alley 2","85","Dennis & June's Sandwich Fare","eat","Compact sandwich counter for breakfasts and lunchtime food.",MH],
["Alley 2","86 / 101–102","The Well Being Place","service","Newcastle University community wellbeing initiative in the market.",MH,"Exact current footprint should be verified."],
["Alley 2","87–88","Feds","eat","Food trader listed on the official market unit plan.",MH],
["Alley 2","89–91 / 96–98","Market Leisure","service","Leisure and entertainment business occupying several units.",MH],
["Alley 2","92–93","Cubanos","eat","Cuban-inspired street food with sandwiches and bold flavours.",MH],
["Alley 1","1–4","Northern Optical Co Ltd","service","Independent optician in a historic Victorian-fronted unit.",MH],
["Alley 1","5–6","King Baby Bagels","eat","Bagel-focused food counter.",MH],
["Alley 1","8–9","Yesterday Society Vintage Boutique","shop","Colourful vintage clothing boutique with a long Grainger Market presence.","Mon–Fri 10:00–17:00 · Sat 10:00–17:30 · Sun closed"],
["Alley 1","10–11","Betfred","service","Betting shop within the market.",MH],
["Alley 1","12–13","Acropolis","eat","Award-winning North East Greek street-food vendor.",MH],
["Alley 1","14–15","Dumpling & Bun","eat","Popular Asian street-food stall specialising in dumplings and buns.",MH],
["Alley 1","16–18","Soju and Gogi","eat","Korean street food and dishes served from a market counter.",MH],
["Alley 1","23 / 70","Grainger Delicatessen","groceries","Long-standing deli serving prepared foods and traditional favourites.",MH,"Published unit reference is unusual and should be verified on site."],
["Alley 1","24–25 / 28–29","Lindsay Bros Quality Fish & Seafood","groceries","Fishmonger selling fresh fish and seafood sourced from the North Sea and beyond.",MH],
["Alley 1","26–27","Chirton Fisheries","groceries","Friendly local fishmonger with strong seafood knowledge.",MH],
["Alley 1","30","North Shore Coffee Co","eat","Speciality coffee, toasties, sweet treats, beans and brewing equipment.","Mon–Sat 08:00–17:00 · Sun closed"],
["Alley 1","31–33","Snackwallah","eat","Highly regarded vegan Indian street-food stall.",MH],
["Alley 1","36–37","Fruit & Nut Company","groceries","Dried fruit, nuts, grains and other weighed pantry goods.",MH],
["Alley 1","38–55","Ruffles","shop","Independent clothing and accessories trader.",MH,"Published unit reference is unusually broad and needs verification."],
["Alley 1","39–41","La Casa Delicatessen","groceries","Deli counter with continental-style foods and ingredients.",MH],
["Alley 1","42–43","La Gamba Bar","eat","Market bar and food spot with a Spanish-influenced identity.",MH],
["Alley 1","44","Shaver Centre","service","Electric shaver and grooming equipment sales and servicing.",MH],
["Alley 1","45–46","Street Food Sri Lanka","eat","Sri Lankan street food built around fragrant curries and traditional flavours.",MH]
].map((r,i)=>({id:"t"+(i+1),z:r[0],u:r[1],n:r[2],c:r[3],d:r[4],h:r[5],x:r[6]||"",s:r[5]==="Closed"?"closed":"current"}));
const U=[
{id:"u1",z:"Alley 4",u:"Unconfirmed",n:"Rice Kitchen",c:"eat",d:"Recent social-media evidence places Rice Kitchen at the end of Alley 4.",h:"Mon–Sat 11:00–16:30 · Sun closed",x:"Current candidate trader; exact unit needs physical verification.",s:"verify"},
{id:"u2",z:"Unconfirmed",u:"Unconfirmed",n:"Blush",c:"service",d:"Long-standing beauty/hair trader listed in the current Grainger Market directory.",h:MH,x:"Exact unit was not established in the V1 spatial baseline.",s:"verify"}
];
