/* V5 Explorer Score research data — checked 1 Sep 2026. */
const EXPLORER_SCORE_CHECKED = "1 Sep 2026";
const EXPLORER_SCORE_METHOD = {
  weights:{quality:35,value:20,service:15,variety:10,atmosphere:10,reliability:10},
  publishThreshold:0.60,
  note:"Explorer Scores combine adjusted multi-source customer ratings with current menu/value evidence and venue reliability. Low-review ratings are shrunk toward a local prior; takeaway-only venues omit atmosphere and renormalise the other dimensions."
};

const EXPLORER_SCORES = {
  "Lagom Speciality Coffee Bar":{score:4.7,confidence:.90,publish:true,d:{quality:4.8,value:4.6,service:4.7,variety:4.3,atmosphere:4.6,reliability:4.8},why:"Exceptional coffee quality and service with strong agreement across a large independent review base.",reviews:[{label:"Review evidence",url:"https://wanderlog.com/place/details/1508774/lagom-coffee-bar"}]},
  "Pink Lane Coffee":{score:4.3,confidence:.91,publish:true,d:{quality:4.5,value:3.9,service:4.1,variety:4.3,atmosphere:4.0,reliability:4.6},why:"Very strong coffee reputation and huge review volume, tempered by more mixed recent service, atmosphere and value feedback.",reviews:[{label:"Review evidence",url:"https://wanderlog.com/place/details/1327234/pink-lane-coffee"},{label:"Tripadvisor",url:"https://www.tripadvisor.co.uk/Restaurant_Review-g186394-d3535348-Reviews-Pink_Lane_Coffee-Newcastle_upon_Tyne_Tyne_and_Wear_England.html"}]},
  "Laneway & Co":{score:4.4,confidence:.89,publish:true,d:{quality:4.5,value:4.0,service:4.4,variety:4.6,atmosphere:4.4,reliability:4.6},why:"Consistently excellent coffee and a broad current menu, with strong service and atmosphere evidence.",reviews:[{label:"Review evidence",url:"https://wanderlog.com/place/details/1414564/laneway--co"}]},
  "Tiny Tiny":{score:4.5,confidence:.86,publish:true,d:{quality:4.6,value:4.1,service:4.5,variety:4.8,atmosphere:4.6,reliability:4.7},why:"Large, well-established review base plus a strong current brunch menu and consistently positive food, coffee and atmosphere feedback.",reviews:[{label:"Review evidence",url:"https://wanderlog.com/place/details/1178995/tiny-tiny"}]},
  "Ouseburn Coffee Co. — Fenwick":{score:4.0,confidence:.68,publish:true,d:{quality:4.4,value:3.6,service:4.0,variety:3.8,atmosphere:3.9,reliability:3.8},why:"Good coffee quality, but the concession has a narrower offer and more mixed service/opening-reliability evidence.",reviews:[{label:"Review evidence",url:"https://wanderlog.com/place/details/7627911/ouseburn-coffee-co"}]},
  "Pumphreys Coffee Centre":{score:4.5,confidence:.78,publish:true,d:{quality:4.6,value:4.6,service:4.5,variety:4.8,atmosphere:4.2,reliability:4.2},why:"Historic specialist roaster with excellent value, knowledgeable service and unusually broad bean/brewing range.",reviews:[{label:"Review evidence",url:"https://restaurantguru.com/Pumphreys-Newcastle-upon-Tyne"}]},
  "North Shore Coffee":{score:4.3,confidence:.76,publish:true,d:{quality:4.7,value:3.9,service:4.1,variety:4.3,atmosphere:4.1,reliability:4.3},why:"Coffee quality scores extremely strongly; value and service evidence is a little more mixed.",reviews:[{label:"Review evidence",url:"https://wanderlog.com/place/details/4367778/north-shore-coffee"}]},
  "Neighbourhood Coffee":{score:4.4,confidence:.61,publish:true,d:{quality:4.6,value:4.1,service:4.5,variety:4.2,atmosphere:4.6,reliability:4.3},why:"Strong coffee, service and sit-in atmosphere, though the city-centre-specific review pool is still relatively modest.",reviews:[{label:"Venue/review evidence",url:"https://www.urbanary.co.uk/venues/newcastle/neighbourhood-coffee"}]},
  "Hatch Coffee":{score:4.7,confidence:.73,publish:true,d:{quality:4.9,value:4.8,service:4.8,variety:4.0,atmosphere:null,reliability:4.6},why:"Outstanding coffee and value sentiment with consistently friendly service; takeaway format means atmosphere is not scored.",reviews:[{label:"Review evidence",url:"https://wanderlog.com/place/details/1414563/hatch-coffee"}]},
  "Olive & Bean":{score:4.4,confidence:.91,publish:true,d:{quality:4.4,value:4.0,service:4.3,variety:4.8,atmosphere:4.4,reliability:4.7},why:"Exceptionally strong evidence volume and a broad current menu, with reliable all-round performance rather than one standout dimension.",reviews:[{label:"Review evidence",url:"https://wanderlog.com/place/details/390762/olive--bean"}]},
  "Olivers Café":{score:4.2,confidence:.69,publish:true,d:{quality:4.2,value:4.5,service:4.3,variety:4.2,atmosphere:4.1,reliability:3.9},why:"Traditional market café with particularly good value and solid service evidence.",reviews:[{label:"Review evidence",url:"https://restaurantguru.com/Olivers-Cafe-Bistro-Newcastle-upon-Tyne"}]},
  "Pet Lamb Patisserie":{score:4.4,confidence:.82,publish:true,d:{quality:4.6,value:4.2,service:4.4,variety:4.5,atmosphere:null,reliability:4.3},why:"Strong cake and bake quality with a substantial independent review history; counter format means atmosphere is not scored.",reviews:[{label:"Review evidence",url:"https://restaurantguru.com/Pet-Lamb-Patisserie-Newcastle-upon-Tyne"}]},
  "The French Oven":{score:4.5,confidence:.75,publish:true,d:{quality:4.6,value:4.5,service:4.5,variety:4.5,atmosphere:null,reliability:4.4},why:"Consistently strong bakery quality, value and service across a broad artisan range.",reviews:[{label:"Review evidence",url:"https://restaurantguru.com/The-French-Oven-Newcastle-upon-Tyne"}]},
  "Eats Cafe":{score:4.1,confidence:.73,publish:true,d:{quality:4.0,value:4.5,service:4.0,variety:4.5,atmosphere:3.8,reliability:4.1},why:"Good-value traditional café with broad choice, balanced by more variable recent service and coffee feedback.",reviews:[{label:"Review evidence",url:"https://wanderlog.com/place/details/3264268/eats-cafe"}]},
  "The Coffee Lounge":{score:4.0,confidence:.64,publish:false,hold:"Score withheld",d:{quality:4.1,value:4.5,service:4.4,variety:4.2,atmosphere:4.0,reliability:2.0},why:"Consumer feedback is generally positive, but the headline score is withheld because current official hygiene evidence is materially concerning.",reviews:[{label:"Customer review evidence",url:"https://citymaps.uk/coffee-shop/newcastle-upon-tyne/the-coffee-lounge/"}],hygiene:{level:"alert",label:"Food hygiene: 1/5 · Major improvement necessary",detail:"Inspected 2 Jun 2026",url:"https://www.eatible.co.uk/north-east/newcastle-upon-tyne/the-coffee-lounge"}},
  "Slice":{score:4.6,confidence:.84,publish:true,d:{quality:4.8,value:4.4,service:4.5,variety:4.2,atmosphere:null,reliability:4.7},why:"Excellent pizza quality and consistency with strong value and fast-service evidence.",reviews:[{label:"Review evidence",url:"https://wanderlog.com/place/details/1469510/slice"}]},
  "Crepes Gourmet":{score:4.6,confidence:.75,publish:true,d:{quality:4.7,value:4.2,service:4.7,variety:4.5,atmosphere:4.5,reliability:4.7},why:"Very strong product and service feedback, broad sweet/savoury choice and current menu evidence.",reviews:[{label:"Review evidence",url:"https://crepesgourmet.com/"}]},
  "Pick Thai":{score:4.5,confidence:.65,publish:true,d:{quality:4.7,value:4.1,service:4.7,variety:4.6,atmosphere:4.4,reliability:4.5},why:"Excellent authenticity and service evidence with a broad Thai menu; confidence is moderated by the smaller review sample.",reviews:[{label:"Review evidence",url:"https://wanderlog.com/place/details/14822152/pick-thai"}]},
  "Bao Down":{score:4.2,confidence:.66,publish:true,d:{quality:4.2,value:4.0,service:4.1,variety:4.5,atmosphere:null,reliability:4.6},why:"Interesting, varied Asian-fusion offer with solid operational evidence, but customer ratings are more mixed than the market leaders.",reviews:[{label:"Review evidence",url:"https://restaurantguru.com/Bao-Down-Newcastle-upon-Tyne"}]},
  "Café one2one":{score:4.4,confidence:.72,publish:true,d:{quality:4.4,value:4.6,service:4.5,variety:4.6,atmosphere:4.1,reliability:4.2},why:"Strong traditional café value, portions and service with a broad breakfast/lunch offer.",reviews:[{label:"Review evidence",url:"https://restaurantguru.com/Cafe-One2one-Newcastle-upon-Tyne-2"}]},
  "Redheads Mac N Cheese":{score:4.3,confidence:.80,publish:true,d:{quality:4.5,value:3.9,service:4.2,variety:4.0,atmosphere:null,reliability:4.6},why:"Very strong food and portion evidence, with value and specialist-menu breadth keeping the overall score below the very top tier.",reviews:[{label:"Review evidence",url:"https://wanderlog.com/place/details/3639322/redheads-mac-n-cheese"},{label:"Tripadvisor",url:"https://www.tripadvisor.co.uk/Restaurant_Review-g186394-d18956145-Reviews-Redheads_mac_n_cheese-Newcastle_upon_Tyne_Tyne_and_Wear_England.html"}]},
  "The Forest Boost":{score:4.4,confidence:.47,publish:false,hold:"Not scored yet",d:{quality:4.4,value:4.0,service:4.5,variety:4.5,atmosphere:4.5,reliability:4.5},why:"Promising product and local evidence, but too little independently attributed review volume and an unresolved unit-location conflict.",reviews:[]},
  "Manhua Cha!":{score:4.6,confidence:.80,publish:true,d:{quality:4.7,value:4.2,service:4.8,variety:4.8,atmosphere:4.3,reliability:4.5},why:"Excellent drink quality and service with a very broad bubble-tea/dessert range and strong multi-source agreement.",reviews:[{label:"Review evidence",url:"https://wanderlog.com/place/details/1283813/manhua-cha"}]},
  "Dennis & June's Sandwich Fare":{score:4.1,confidence:.47,publish:false,hold:"Score withheld",d:{quality:4.1,value:4.8,service:4.2,variety:4.0,atmosphere:null,reliability:2.5},why:"Long-standing value reputation, but independent review evidence is thin and current official inspection findings require separate prominence.",reviews:[],hygiene:{level:"alert",label:"Food hygiene: improvement necessary",detail:"Official inspection May 2026; handling and structural cleanliness concerns recorded",url:"https://ratings.food.gov.uk/business/235705/dennis-junes-sandwich-fayre-newcastle-upon-tyne"}},
  "Cubanos":{score:4.6,confidence:.78,publish:true,d:{quality:4.8,value:4.6,service:4.7,variety:4.4,atmosphere:4.2,reliability:4.6},why:"Excellent food, portions, service and value with strong recent customer agreement.",reviews:[{label:"Review evidence",url:"https://wanderlog.com/place/details/11668649/cubanos"}]},
  "King Baby Bagels":{score:4.7,confidence:.88,publish:true,d:{quality:4.9,value:4.4,service:4.8,variety:4.4,atmosphere:null,reliability:4.7},why:"Exceptional independent ratings at meaningful volume, backed by consistently strong bagel quality and service.",reviews:[{label:"Review evidence",url:"https://restaurantguru.com/Kingbabybagels-Newcastle-upon-Tyne"}]},
  "Acropolis":{score:4.5,confidence:.80,publish:true,d:{quality:4.6,value:4.3,service:4.5,variety:4.4,atmosphere:4.3,reliability:4.6},why:"Strong, consistent Greek street-food quality with good value and fast/friendly service evidence.",reviews:[{label:"Review evidence",url:"https://wanderlog.com/place/details/3984208/acropolis-grainger-market"}]},
  "Dumpling & Bun":{score:4.4,confidence:.67,publish:true,d:{quality:4.7,value:4.4,service:4.5,variety:4.1,atmosphere:3.8,reliability:3.8},why:"Excellent dumpling quality and value; the smaller review base and somewhat less consistent operational evidence reduce confidence.",reviews:[{label:"Review evidence",url:"https://wanderlog.com/place/details/14232990/dumpling-and-bun"},{label:"Tripadvisor",url:"https://www.tripadvisor.com/Restaurant_Review-g186394-d24074777-Reviews-Dumpling_Bun-Newcastle_upon_Tyne_Tyne_and_Wear_England.html"}]},
  "Soju and Gogi":{score:4.2,confidence:.63,publish:true,d:{quality:4.2,value:4.2,service:4.1,variety:4.5,atmosphere:4.1,reliability:3.7},why:"Distinctive Korean street-food range with solid quality/value evidence, but weaker consistency and review depth than the leaders.",reviews:[{label:"Review evidence",url:"https://www.familyfriendlyuk.co.uk/restaurants/soju-and-gogi-express-newcastle-upon-tyne/"}]},
  "Snackwallah":{score:4.7,confidence:.92,publish:true,d:{quality:4.8,value:4.7,service:4.7,variety:4.5,atmosphere:4.4,reliability:4.8},why:"The strongest evidence profile in the set: exceptional vegan Indian food, value and service with substantial cross-platform agreement.",reviews:[{label:"Review evidence",url:"https://restaurantguru.com/Snackwallah-Newcastle-upon-Tyne"}]},
  "La Gamba Vermuteria":{score:4.5,confidence:.49,publish:false,hold:"Not scored yet",d:{quality:4.5,value:3.9,service:4.5,variety:4.8,atmosphere:4.9,reliability:4.5},why:"Excellent menu, atmosphere and primary-source evidence, but not enough independent venue-specific review volume yet.",reviews:[]},
  "Street Food Sri Lanka":{score:4.4,confidence:.51,publish:false,hold:"Not scored yet",d:{quality:4.6,value:4.2,service:4.3,variety:4.7,atmosphere:4.2,reliability:4.4},why:"Very promising food and editorial evidence, but trader-specific independent review volume remains too thin for a headline score.",reviews:[{label:"Grainger Market reviews",url:"https://www.tripadvisor.co.uk/Restaurant_Review-g186394-d17352698-Reviews-Grainger_Market-Newcastle_upon_Tyne_Tyne_and_Wear_England.html"}]},
  "Rice Kitchen":{score:4.5,confidence:.48,publish:false,hold:"Not scored yet",d:{quality:4.6,value:4.5,service:4.5,variety:4.2,atmosphere:4.2,reliability:4.7},why:"Strong early product, value and operational evidence, but the business is too new for a mature independent review pool.",reviews:[{label:"Current venue evidence",url:"https://www.getintonewcastle.co.uk/venues/the-rice-kitchen"}],hygiene:{level:"good",label:"Food hygiene: 5/5",detail:"Official inspection May 2026",url:"https://ratings.food.gov.uk/business/1911979/rice-kitchen-newcastle-upon-tyne"}},
  "Noodle Box & Chinese Burger":{score:4.6,confidence:.55,publish:false,hold:"Not scored yet",d:{quality:4.8,value:4.4,service:4.7,variety:4.5,atmosphere:4.4,reliability:4.5},why:"Extremely positive early reports and authentic specialist food, but the independently attributed review count is not robust enough yet.",reviews:[{label:"Review evidence",url:"https://es.restaurantguru.com/U-Noodle-Newcastle-upon-Tyne"}]},
  "Lindsay's on the go":{score:4.5,confidence:.43,publish:false,hold:"Not scored yet",d:{quality:4.5,value:4.3,service:4.5,variety:4.4,atmosphere:null,reliability:4.6},why:"Excellent current primary information and seafood range, but insufficient independent customer-review evidence.",reviews:[]},
  "Firebrick Brewery":{score:4.2,confidence:.56,publish:false,hold:"Not scored yet",d:{quality:4.2,value:4.2,service:3.5,variety:4.8,atmosphere:4.0,reliability:4.5},why:"Strong specialist beer range and positive expert evidence, but the venue-specific independent review sample remains very small.",reviews:[{label:"Specialist review",url:"https://www.newbrewthursday.uk/p/firebrick-taproom"}],hygiene:{level:"good",label:"Food hygiene: 5/5",detail:"Current 2026 inspection evidence",url:"https://ratings.food.gov.uk/cy/business/1486503/firebrick-brewery-ltd-newcastle-upon-tyne"}},
  "La Casa Delicatessen":{score:4.3,confidence:.78,publish:true,d:{quality:4.5,value:4.1,service:4.0,variety:4.7,atmosphere:4.3,reliability:4.4},why:"Strong Spanish deli range and consistently positive food/wine feedback, with good independent review depth.",reviews:[{label:"Review evidence",url:"https://wanderlog.com/place/details/3982737/la-casa-delicatessen"}]}
};

const EXPLORER_SCORE_ALIASES = {
  "Pumphreys Coffee":"Pumphreys Coffee Centre",
  "North Shore Coffee Co":"North Shore Coffee",
  "North Shore Coffee Co.":"North Shore Coffee",
  "Soju and Gogi Express":"Soju and Gogi",
  "La Gamba Bar":"La Gamba Vermuteria"
};
function explorerScoreFor(name){return EXPLORER_SCORES[EXPLORER_SCORE_ALIASES[name]||name]||null;}
